### ISSUE TITLE
字体非常小

### ISSUE THREAD

**Issue by x000zh** [dnasdw/SharedFontTool#2]
选择第一个字体（Chinese & Japanese)，在new 3DSLL上字体都错位了，比如FBI上行距会有问题， [异史战国传：宿业](https://lovecia.com/115/)字体非常小。

**Comment by dnasdw** [comment]
使用说明：

1.下载并解压缩
2.复制CIA到3DS上或利用3DS模拟器打开
3.进入本SFT2工具后，直接按A一键切换至简易字库，并按START键退出
4.还原时只要进入本SFT2工具后，直接按SELECT一键切换至正常字库环境，并按START键退出即可。

资源说明：

一、新版特性
·SFT从1.x版升级到2.0版之后，大家首先会发现软件本身的大小变化了。因为SFT2.0版当中内嵌了3个优化过的字库和4个原版字库。理论不再需要玩家自行向SD卡里复制font文件夹了，用起来更加傻白甜——当然，但如果高端玩家想替换字体仍然可以利用7-10的功能随自身喜好来替换字体。
·SFT2.0版开启了上屏显示，而且主要部分都显示在上屏，下屏只显示当前操作的部分日志，有研究欲望的高端玩家可以看看。
·SFT2.0版取消了1.x版的一键切换字库(因为字库变多，把3DS主机上所有按键都用上的话，感觉有点傻)。

二、操作方法
·操作改为用十字键的上下左右来切换选择字库，按A来执行切换，保留按SELECT键还原字库和按START键退出的功能。
·上键将光标移动到上一个字库(如果已经是第一个字库，则将光标移动到最后一个字库)。
·下键将光标移动到下一个字库(如果已经是最后一个字库，则将光标移动到第一个字库)。
·左键将光标移动到第一个字库。
·右键将光标移动到最后一个字库。

三、颜色显示
·字库显示为绿色代表可以安全切换。
·字库显示为黄色代表切换之后回到主界面可能会崩溃。
·字库显示为红色代表切换之后回到主界面肯定会崩溃(用户无法执行此类操作)。

四、各字库说明
0. romfs: Chinese&Japanese (C/T/J/U/E)  内嵌调整字库，整合了官方简体中文，繁体中文，日美欧字库中的所有字符，以保证可以在所有机器上切换，玩非官方汉化版游戏强烈推荐切换到这个字库。
1. romfs: modified official cn (C)      内嵌调整字库，调整了官方简体中文字库的分页，以保证可以在韩版机上切换，玩官方简体中文游戏推荐切换到这个字库。
2. romfs: modified official std (J/U/E) 内嵌调整字库，调整了官方日美欧字库的分页，以保证可以在神游机和韩版机上切换，玩官方日美欧游戏推荐切换到这个字库。
3. romfs: official cn (C)               内嵌官方字库，非韩版机都可以切换到这个字库，玩官方简体中文游戏推荐切换到这个字库，0号字库和1号字库为此字库替代品。
4. romfs: official tw (T)               内嵌官方字库，只有港台版机可以切换到这个字库，几乎无用，0号字库为此字库替代品，如果想在非港台版机器上玩官方繁体中文游戏，请切换到0号字库。
5. romfs: official std (J/U/E)          内嵌官方字库，非神游机且非韩版机都可以切换到这个字库，玩官方日美欧游戏推荐切换到这个字库，0号字库和2号字库为此字库替代品。
6. romfs: official kr (K)               内嵌官方字库，所有机器都可以切换到这个字库，玩官方韩文游戏推荐切换到这个字库，这个字库不需要替代品，呀哈哈！
7. sdmc:  /font/cn/cbf_zh-Hans-CN.bcfnt SD卡外挂字库，原为官方字库，可能被用户替换成其他优化字库，不推荐使用。
8. sdmc:  /font/tw/cbf_zh-Hant-TW.bcfnt SD卡外挂字库，原为官方字库，可能被用户替换成其他优化字库，不推荐使用。
9. sdmc:  /font/std/cbf_std.bcfnt       SD卡外挂字库，原为官方字库，可能被用户替换成其他优化字库，不推荐使用。
10. sdmc:  /font/kr/cbf_ko-Hang-KR.bcfnt SD卡外挂字库，原为官方字库，可能被用户替换成其他优化字库，不推荐使用。

五、来自作者的救赎
·拯救韩版机：以前韩版机因为字库页数问题而无法玩系统字库的汉化游戏，有了SFT2，妈妈再也不担心我韩版机玩不了系统字库的汉化游戏啦！
·拯救神游机：以前神游机因为字库页数问题而无法玩类似《超级机器人大战UX/BX》等尚未汉化的系统字库日版游戏，自从有了SFT2，你们懂的！
·拯救日版机：以前日版机因为字库页数问题而无法玩类似《马车7》、《马3立》等只有港中系统字库的港版游戏，SFT2在手，不惧繁体字我有！

**Comment by dnasdw** [comment]
0号字体为了整合简繁日三种字体，所以字号调小了，在大部分游戏中表现正常（官方会自己设定一个需要的字号），在少数游戏或应用中显示过小，比如PXZ，FBI等（开发者没有去设置字号，直接使用了默认的）。

这种情况要显示简体中文，可以使用1号字体。

**Comment by x000zh** [comment]
确实3ds本身也不能跨区这个使用场景不是很高，用对应字体应付大多数情况了。
