### ISSUE TITLE
大？

### ISSUE THREAD

**Issue by Zer0xPoint** [dnasdw/SharedFontTool#3]
Mean's 3DSLL?or New 3DS?

**Comment by dnasdw** [comment]
No.
大(Big) for games are running on (SYSTEM_MODE := 80MB) mode.
For example, Super Mario Maker for Nintendo 3DS, Captain Toad: Treasure Tracker.
Usage like BootNTR Mode3.

**Comment by dnasdw** [comment]
为啥不说中文呢?

**Comment by zongren** [comment]
老哥再解释一遍。。

**Comment by dnasdw** [comment]
就是有一种游戏需要使用80M内存(普通游戏只使用64M内存)，这种游戏启动前会“重启”3DS，导致字库工具做的操作失效，所以编译了一个单独的使用80M内存模式的字库工具，也就是相当于在启动字库工具的时候3DS完成重启，这时候再切到另一个80M内存模式的游戏时就不会在重启了，当然如果从80M模式直接退出，也会导致3DS“重启”，所以只能切换应用。
