### ISSUE TITLE
选择第一个Chinese&Japanese后，不显示英文字符

### ISSUE THREAD

**Issue by zongren** [dnasdw/SharedFontTool#6]
机型：新大三
系统：11.13.0-45u
SharedFontTool版本：3.1

**Comment by dnasdw** [comment]
你先换个游戏试试，可能是游戏导致的？

**Comment by zongren** [comment]
对不起，没说清楚，桌面就不显示英文了，例如Wi-Fi信号那里的internet

**Comment by dnasdw** [comment]
正常，在主菜单理论都会显示异常，毕竟强行覆盖了某块内存。

**Comment by zongren** [comment]
好的，多谢
